[rospy.client][INFO] 2020-11-03 00:00:36,587: init_node, name[/rostful_server], pid[4975]
[xmlrpc][INFO] 2020-11-03 00:00:36,587: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-03 00:00:36,587: Started XML-RPC server [http://freight1207:35607/]
[rospy.init][INFO] 2020-11-03 00:00:36,587: ROS Slave URI: [http://freight1207:35607/]
[rospy.impl.masterslave][INFO] 2020-11-03 00:00:36,587: _ready: http://freight1207:35607/
[xmlrpc][INFO] 2020-11-03 00:00:36,588: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-03 00:00:36,588: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-03 00:00:36,687: registered with master
[rospy.rosout][INFO] 2020-11-03 00:00:36,688: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-03 00:00:36,689: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-03 00:00:36,690: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-03 00:00:36,696: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-03 00:00:36,924: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,753: topic[/current/pose] adding connection to [http://freight1207:57061/], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,755: topic[/current/pose] adding connection to [http://freight1207:35607/], count 1
[rospy.internal][INFO] 2020-11-03 00:00:37,756: topic[/enable_software_runstop] adding connection to [http://freight1207:35607/], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,757: topic[/local_control/initialpose] adding connection to [http://freight1207:35607/], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,758: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,759: topic[/local_control/cancel] adding connection to [http://freight1207:35607/], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,760: topic[/local_control/goto] adding connection to [http://freight1207:35607/], count 0
[rosout][INFO] 2020-11-03 00:00:37,760: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-03 00:00:37,761: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,761: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,761: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,761: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 00:00:37,790: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2020-11-03 00:00:37,875: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-03 00:00:37,875: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-03 00:00:37,926: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2020-11-03 00:01:39,034: topic[/current/pose] adding connection to [http://freight1207:48902/], count 2
[rospy.internal][WARNING] 2020-11-03 00:01:39,130: Unknown error initiating TCP/IP socket to freight1207:39710 (http://freight1207:57061/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-03 00:01:39,130: topic[/current/pose] removing connection to http://freight1207:57061/
[rospy.internal][INFO] 2020-11-03 00:01:39,215: topic[/local_control/goto] adding connection to [/local_control_navigation], count 2
[rospy.internal][INFO] 2020-11-03 00:01:39,215: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][INFO] 2020-11-03 00:01:39,215: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 2
[rospy.internal][INFO] 2020-11-03 00:01:39,216: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-11-03 00:01:39,216: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 2
[rospy.internal][INFO] 2020-11-03 00:01:39,216: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][WARNING] 2020-11-03 00:01:51,136: Unknown error initiating TCP/IP socket to freight1207:42501 (http://freight1207:48902/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-03 00:01:51,136: topic[/current/pose] removing connection to http://freight1207:48902/
[rosout][INFO] 2020-11-03 00:01:57,280: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-03 00:01:57,280: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-03 00:01:57,283: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:01:57,283: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-11-03 00:01:57,284: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:01:57,284: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-11-03 00:01:57,284: Unable to initiate TCP/IP socket to freight1207:57408 (http://freight1207:35607/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-11-03 00:01:57,284: Unable to initiate TCP/IP socket to freight1207:57408 (http://freight1207:35607/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 00:01:57,284: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-03 00:01:57,285: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:01:57,285: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-11-03 00:01:57,285: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:01:57,285: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-11-03 00:01:57,285: Unable to initiate TCP/IP socket to freight1207:57408 (http://freight1207:35607/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 00:01:57,286: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:01:57,286: topic[/enable_software_runstop] removing connection to http://freight1207:35607/
[rospy.internal][ERROR] 2020-11-03 00:01:57,286: Unable to initiate TCP/IP socket to freight1207:57408 (http://freight1207:35607/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 00:01:57,286: topic[/local_control/initialpose] removing connection to http://freight1207:35607/
[rospy.internal][INFO] 2020-11-03 00:01:57,286: topic[/local_control/goto] removing connection to http://freight1207:35607/
[rospy.internal][ERROR] 2020-11-03 00:01:57,286: Unable to initiate TCP/IP socket to freight1207:57408 (http://freight1207:35607/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 00:01:57,286: topic[/local_control/cancel] removing connection to http://freight1207:35607/
[rospy.internal][INFO] 2020-11-03 00:01:57,287: topic[/current/pose] removing connection to http://freight1207:35607/
[rospy.impl.masterslave][INFO] 2020-11-03 00:01:57,287: Closing
[rospy.core][INFO] 2020-11-03 00:01:57,418: signal_shutdown [atexit]
[rospy.client][INFO] 2020-11-03 00:02:11,662: init_node, name[/rostful_server], pid[6643]
[xmlrpc][INFO] 2020-11-03 00:02:11,663: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-03 00:02:11,663: Started XML-RPC server [http://freight1207:36236/]
[rospy.init][INFO] 2020-11-03 00:02:11,663: ROS Slave URI: [http://freight1207:36236/]
[rospy.impl.masterslave][INFO] 2020-11-03 00:02:11,663: _ready: http://freight1207:36236/
[xmlrpc][INFO] 2020-11-03 00:02:11,663: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-03 00:02:11,664: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-03 00:02:11,763: registered with master
[rospy.rosout][INFO] 2020-11-03 00:02:11,763: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-03 00:02:11,765: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-03 00:02:11,766: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-03 00:02:11,770: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-03 00:02:11,973: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,818: topic[/enable_software_runstop] adding connection to [/software_runstop], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,829: topic[/current/pose] adding connection to [http://freight1207:36236/], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,831: topic[/enable_software_runstop] adding connection to [http://freight1207:36236/], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,832: topic[/local_control/cancel] adding connection to [http://freight1207:36236/], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,833: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,834: topic[/local_control/initialpose] adding connection to [http://freight1207:36236/], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,835: topic[/local_control/goto] adding connection to [http://freight1207:36236/], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,835: topic[/enable_software_runstop] adding connection to [/rostful_server], count 1
[rospy.internal][INFO] 2020-11-03 00:02:12,835: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,836: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 00:02:12,836: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rosout][INFO] 2020-11-03 00:02:13,466: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-03 00:02:15,797: topic[/current/pose] adding connection to [http://freight1207:39820/], count 1
[rospy.internal][INFO] 2020-11-03 00:02:15,923: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-03 00:02:15,923: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-03 00:02:15,923: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rosout][WARNING] 2020-11-03 00:02:20,590: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -7.32
    locationY: -2.51
    orientation: 0.102
  - 
    locationX: -5.89
    locationY: -1.99
    orientation: 0.17 to topic /local_control/goto
[rosout][WARNING] 2020-11-03 00:03:41,806: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -7.32
    locationY: -2.51
    orientation: 0.102
  - 
    locationX: -5.89
    locationY: -1.99
    orientation: 0.17 to topic /local_control/goto
[rosout][WARNING] 2020-11-03 00:03:58,910: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -7.32
    locationY: -2.51
    orientation: 0.102
  - 
    locationX: -5.89
    locationY: -1.99
    orientation: 0.17 to topic /local_control/goto
[rosout][WARNING] 2020-11-03 00:04:03,552: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -7.32
    locationY: -2.51
    orientation: 0.102
  - 
    locationX: -5.89
    locationY: -1.99
    orientation: 0.17 to topic /local_control/goto
[rosout][INFO] 2020-11-03 00:04:50,983: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-03 00:04:50,983: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-03 00:04:50,987: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-11-03 00:04:50,987: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:04:50,987: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:04:50,987: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][INFO] 2020-11-03 00:04:50,987: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-03 00:04:50,988: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:04:50,988: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-11-03 00:04:50,988: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-11-03 00:04:50,989: Unable to initiate TCP/IP socket to freight1207:38171 (http://freight1207:36236/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-11-03 00:04:50,989: Unable to initiate TCP/IP socket to freight1207:38171 (http://freight1207:36236/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 00:04:50,989: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-11-03 00:04:50,989: Unable to initiate TCP/IP socket to freight1207:38171 (http://freight1207:36236/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-11-03 00:04:50,989: Unable to initiate TCP/IP socket to freight1207:38171 (http://freight1207:36236/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 00:04:50,989: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 00:04:50,990: topic[/enable_software_runstop] removing connection to http://freight1207:36236/
[rospy.internal][INFO] 2020-11-03 00:04:50,990: topic[/local_control/initialpose] removing connection to http://freight1207:36236/
[rospy.internal][ERROR] 2020-11-03 00:04:50,990: Unable to initiate TCP/IP socket to freight1207:38171 (http://freight1207:36236/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 00:04:50,990: topic[/local_control/goto] removing connection to http://freight1207:36236/
[rospy.internal][INFO] 2020-11-03 00:04:50,990: topic[/local_control/cancel] removing connection to http://freight1207:36236/
[rospy.internal][INFO] 2020-11-03 00:04:50,990: topic[/current/pose] removing connection to http://freight1207:36236/
[rospy.internal][INFO] 2020-11-03 00:04:50,990: topic[/current/pose] removing connection to http://freight1207:39820/
[rospy.impl.masterslave][INFO] 2020-11-03 00:04:50,990: Closing
[rospy.core][INFO] 2020-11-03 00:04:51,094: signal_shutdown [atexit]
