[rospy.client][INFO] 2018-12-04 19:20:47,047: init_node, name[/rostful_server], pid[20198]
[xmlrpc][INFO] 2018-12-04 19:20:47,048: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 19:20:47,048: Started XML-RPC server [http://freight1207:51187/]
[rospy.init][INFO] 2018-12-04 19:20:47,048: ROS Slave URI: [http://freight1207:51187/]
[rospy.impl.masterslave][INFO] 2018-12-04 19:20:47,048: _ready: http://freight1207:51187/
[xmlrpc][INFO] 2018-12-04 19:20:47,049: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 19:20:47,049: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 19:20:47,148: registered with master
[rospy.rosout][INFO] 2018-12-04 19:20:47,149: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 19:20:47,150: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 19:20:47,151: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-04 19:20:47,156: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-04 19:20:47,385: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-04 19:20:48,183: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-04 19:20:48,217: topic[/software_runstop_enabled] adding connection to [http://freight1207:51187/], count 0
[rospy.internal][INFO] 2018-12-04 19:20:48,217: topic[/software_runstop_enabled] adding connection to [http://freight1207:57811/], count 0
[rospy.internal][INFO] 2018-12-04 19:20:48,218: topic[/local_control/initialpose] adding connection to [http://freight1207:51187/], count 0
[rospy.internal][INFO] 2018-12-04 19:20:48,219: topic[/software_runstop_enabled] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:20:48,220: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:23:54,942: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rosout][INFO] 2018-12-04 19:27:42,398: rostful_server: Shutting down the server
[rospy.core][INFO] 2018-12-04 19:27:42,398: signal_shutdown [Closing]
[rospy.internal][INFO] 2018-12-04 19:27:42,401: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:27:42,401: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2018-12-04 19:27:42,401: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-04 19:27:42,401: topic[/software_runstop_enabled] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:27:42,402: topic[/local_control/initialpose] removing connection to http://freight1207:51187/
[rospy.internal][INFO] 2018-12-04 19:27:42,402: topic[/software_runstop_enabled] removing connection to http://freight1207:51187/
[rospy.internal][ERROR] 2018-12-04 19:27:42,402: Unable to initiate TCP/IP socket to freight1207:55762 (http://freight1207:51187/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 19:27:42,402: topic[/software_runstop_enabled] removing connection to http://freight1207:57811/
[rospy.internal][ERROR] 2018-12-04 19:27:42,402: Unable to initiate TCP/IP socket to freight1207:55762 (http://freight1207:51187/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.impl.masterslave][INFO] 2018-12-04 19:27:42,402: Closing
[rospy.core][INFO] 2018-12-04 19:27:42,534: signal_shutdown [atexit]
[rospy.client][INFO] 2018-12-04 19:27:44,356: init_node, name[/rostful_server], pid[22052]
[xmlrpc][INFO] 2018-12-04 19:27:44,356: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 19:27:44,357: Started XML-RPC server [http://freight1207:38385/]
[rospy.init][INFO] 2018-12-04 19:27:44,357: ROS Slave URI: [http://freight1207:38385/]
[rospy.impl.masterslave][INFO] 2018-12-04 19:27:44,357: _ready: http://freight1207:38385/
[xmlrpc][INFO] 2018-12-04 19:27:44,357: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 19:27:44,357: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 19:27:44,457: registered with master
[rospy.rosout][INFO] 2018-12-04 19:27:44,457: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 19:27:44,459: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 19:27:44,460: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-04 19:27:44,464: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-04 19:27:44,677: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-04 19:27:45,495: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-04 19:27:45,523: topic[/software_runstop_enabled] adding connection to [http://freight1207:57811/], count 0
[rospy.internal][INFO] 2018-12-04 19:27:45,524: topic[/software_runstop_enabled] adding connection to [http://freight1207:38385/], count 1
[rospy.internal][INFO] 2018-12-04 19:27:45,525: topic[/local_control/initialpose] adding connection to [http://freight1207:38385/], count 0
[rospy.internal][INFO] 2018-12-04 19:27:45,526: topic[/local_control/goto] adding connection to [http://freight1207:38385/], count 0
[rospy.internal][INFO] 2018-12-04 19:27:45,527: topic[/software_runstop_enabled] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:27:45,527: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:27:45,527: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:27:45,678: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-04 19:27:45,679: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rosout][WARNING] 2018-12-04 19:27:50,401: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 1.38
    locationY: 2.08
    orientation: 1.0 to topic /local_control/goto
[rosout][INFO] 2018-12-04 19:28:13,341: rostful_server: Shutting down the server
[rospy.core][INFO] 2018-12-04 19:28:13,341: signal_shutdown [Closing]
[rospy.internal][INFO] 2018-12-04 19:28:13,345: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:28:13,346: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2018-12-04 19:28:13,346: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:28:13,346: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][INFO] 2018-12-04 19:28:13,346: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2018-12-04 19:28:13,347: Unable to initiate TCP/IP socket to freight1207:40495 (http://freight1207:38385/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 19:28:13,347: topic[/software_runstop_enabled] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:28:13,347: topic[/local_control/initialpose] removing connection to http://freight1207:38385/
[rospy.internal][INFO] 2018-12-04 19:28:13,348: topic[/local_control/goto] removing connection to http://freight1207:38385/
[rospy.internal][ERROR] 2018-12-04 19:28:13,348: Unable to initiate TCP/IP socket to freight1207:40495 (http://freight1207:38385/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 19:28:13,348: Unable to initiate TCP/IP socket to freight1207:40495 (http://freight1207:38385/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 19:28:13,348: topic[/software_runstop_enabled] removing connection to http://freight1207:57811/
[rospy.internal][WARNING] 2018-12-04 19:28:13,349: Unknown error initiating TCP/IP socket to freight1207:57870 (http://freight1207:57811/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2018-12-04 19:28:13,350: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2018-12-04 19:28:13,350: topic[/software_runstop_enabled] removing connection to http://freight1207:38385/
[rospy.impl.masterslave][INFO] 2018-12-04 19:28:13,350: Closing
[rospy.core][INFO] 2018-12-04 19:28:13,965: signal_shutdown [atexit]
[rospy.client][INFO] 2018-12-04 19:29:18,323: init_node, name[/rostful_server], pid[23799]
[xmlrpc][INFO] 2018-12-04 19:29:18,323: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 19:29:18,323: Started XML-RPC server [http://freight1207:39731/]
[rospy.init][INFO] 2018-12-04 19:29:18,323: ROS Slave URI: [http://freight1207:39731/]
[rospy.impl.masterslave][INFO] 2018-12-04 19:29:18,323: _ready: http://freight1207:39731/
[xmlrpc][INFO] 2018-12-04 19:29:18,324: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 19:29:18,324: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 19:29:18,424: registered with master
[rospy.rosout][INFO] 2018-12-04 19:29:18,424: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 19:29:18,425: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 19:29:18,426: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-04 19:29:18,430: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-04 19:29:18,715: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-04 19:29:19,464: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-04 19:29:19,490: topic[/software_runstop_enabled] adding connection to [http://freight1207:57811/], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,491: topic[/software_runstop_enabled] adding connection to [http://freight1207:39731/], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,492: topic[/local_control/cancel] adding connection to [http://freight1207:39731/], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,493: topic[/local_control/initialpose] adding connection to [http://freight1207:39731/], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,494: topic[/local_control/goto] adding connection to [http://freight1207:39731/], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,495: topic[/software_runstop_enabled] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,495: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,495: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,495: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:29:19,718: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2018-12-04 19:29:19,719: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-04 19:29:19,719: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rosout][WARNING] 2018-12-04 19:29:35,613: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 1.38
    locationY: 2.08
    orientation: 1.0 to topic /local_control/goto
[rosout][WARNING] 2018-12-04 19:32:04,083: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 3.55
    locationY: 1.66
    orientation: 1.0 to topic /local_control/goto
[rosout][WARNING] 2018-12-04 19:32:28,702: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 3.55
    locationY: 1.66
    orientation: 1.0 to topic /local_control/goto
[rosout][WARNING] 2018-12-04 19:32:57,068: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 3.55
    locationY: 1.66
    orientation: 1.0 to topic /local_control/goto
[rosout][WARNING] 2018-12-04 19:33:20,255: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 3.55
    locationY: 1.66
    orientation: 1.0 to topic /local_control/goto
[rosout][WARNING] 2018-12-04 19:33:21,256: publishing data: True to topic /local_control/cancel
[rosout][INFO] 2018-12-04 19:34:25,333: rostful_server: Shutting down the server
[rospy.core][INFO] 2018-12-04 19:34:25,333: signal_shutdown [Closing]
[rospy.internal][INFO] 2018-12-04 19:34:25,336: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:34:25,337: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2018-12-04 19:34:25,337: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:34:25,337: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2018-12-04 19:34:25,337: Unable to initiate TCP/IP socket to freight1207:35775 (http://freight1207:39731/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 19:34:25,337: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2018-12-04 19:34:25,337: Unable to initiate TCP/IP socket to freight1207:35775 (http://freight1207:39731/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 19:34:25,338: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:34:25,338: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][INFO] 2018-12-04 19:34:25,338: topic[/software_runstop_enabled] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 19:34:25,338: topic[/local_control/initialpose] removing connection to http://freight1207:39731/
[rospy.internal][ERROR] 2018-12-04 19:34:25,338: Unable to initiate TCP/IP socket to freight1207:35775 (http://freight1207:39731/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 19:34:25,338: topic[/local_control/goto] removing connection to http://freight1207:39731/
[rospy.internal][INFO] 2018-12-04 19:34:25,339: topic[/local_control/cancel] removing connection to http://freight1207:39731/
[rospy.internal][ERROR] 2018-12-04 19:34:25,339: Unable to initiate TCP/IP socket to freight1207:35775 (http://freight1207:39731/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 19:34:25,339: topic[/software_runstop_enabled] removing connection to http://freight1207:57811/
[rospy.internal][INFO] 2018-12-04 19:34:25,339: topic[/software_runstop_enabled] removing connection to http://freight1207:39731/
[rospy.impl.masterslave][INFO] 2018-12-04 19:34:25,339: Closing
[rospy.core][INFO] 2018-12-04 19:34:25,471: signal_shutdown [atexit]
[rospy.client][INFO] 2018-12-04 19:35:04,172: init_node, name[/rostful_server], pid[25106]
[xmlrpc][INFO] 2018-12-04 19:35:04,173: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 19:35:04,173: Started XML-RPC server [http://freight1207:32856/]
[rospy.impl.masterslave][INFO] 2018-12-04 19:35:04,173: _ready: http://freight1207:32856/
[rospy.init][INFO] 2018-12-04 19:35:04,173: ROS Slave URI: [http://freight1207:32856/]
[xmlrpc][INFO] 2018-12-04 19:35:04,174: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 19:35:04,174: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 19:35:04,274: registered with master
[rospy.rosout][INFO] 2018-12-04 19:35:04,274: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 19:35:04,275: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 19:35:04,276: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-04 19:35:04,280: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-04 19:35:04,555: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-04 19:35:05,314: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-04 19:35:05,340: topic[/enable_software_runstop] adding connection to [http://freight1207:32856/], count 0
[rospy.internal][INFO] 2018-12-04 19:35:05,341: topic[/local_control/cancel] adding connection to [http://freight1207:32856/], count 0
[rospy.internal][INFO] 2018-12-04 19:35:05,342: topic[/local_control/initialpose] adding connection to [http://freight1207:32856/], count 0
[rospy.internal][INFO] 2018-12-04 19:35:05,343: topic[/local_control/goto] adding connection to [http://freight1207:32856/], count 0
[rospy.internal][INFO] 2018-12-04 19:35:05,343: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:35:05,344: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:35:05,344: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:35:05,344: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 19:35:05,359: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rosout][WARNING] 2018-12-04 19:35:10,294: publishing data: True to topic /enable_software_runstop
[rosout][WARNING] 2018-12-04 19:35:26,043: publishing data: False to topic /enable_software_runstop
[rosout][INFO] 2018-12-04 20:25:43,457: rostful_server: Shutting down the server
[rospy.core][INFO] 2018-12-04 20:25:43,457: signal_shutdown [Closing]
[rospy.internal][INFO] 2018-12-04 20:25:43,460: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 20:25:43,461: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-04 20:25:43,461: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 20:25:43,461: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 20:25:43,462: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-04 20:25:43,462: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-04 20:25:43,462: Unable to initiate TCP/IP socket to freight1207:54980 (http://freight1207:32856/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 20:25:43,462: Unable to initiate TCP/IP socket to freight1207:54980 (http://freight1207:32856/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 20:25:43,462: topic[/enable_software_runstop] removing connection to http://freight1207:32856/
[rospy.internal][ERROR] 2018-12-04 20:25:43,462: Unable to initiate TCP/IP socket to freight1207:54980 (http://freight1207:32856/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 20:25:43,463: Unable to initiate TCP/IP socket to freight1207:54980 (http://freight1207:32856/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 20:25:43,463: topic[/local_control/initialpose] removing connection to http://freight1207:32856/
[rospy.internal][INFO] 2018-12-04 20:25:43,463: topic[/local_control/goto] removing connection to http://freight1207:32856/
[rospy.internal][INFO] 2018-12-04 20:25:43,463: topic[/local_control/cancel] removing connection to http://freight1207:32856/
[rospy.impl.masterslave][INFO] 2018-12-04 20:25:43,463: Closing
[rospy.core][INFO] 2018-12-04 20:25:44,078: signal_shutdown [atexit]
[rospy.client][INFO] 2018-12-04 20:42:16,997: init_node, name[/rostful_server], pid[6451]
[xmlrpc][INFO] 2018-12-04 20:42:16,998: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 20:42:16,998: Started XML-RPC server [http://freight1207:56012/]
[rospy.init][INFO] 2018-12-04 20:42:16,998: ROS Slave URI: [http://freight1207:56012/]
[rospy.impl.masterslave][INFO] 2018-12-04 20:42:16,998: _ready: http://freight1207:56012/
[xmlrpc][INFO] 2018-12-04 20:42:16,998: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 20:42:16,999: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 20:42:17,098: registered with master
[rospy.rosout][INFO] 2018-12-04 20:42:17,098: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 20:42:17,100: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 20:42:17,101: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-04 20:42:17,105: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-04 20:42:17,318: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-04 20:42:18,147: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-04 20:42:18,164: topic[/remote_control] adding connection to [http://freight1207:56012/], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,166: topic[/enable_software_runstop] adding connection to [http://freight1207:56012/], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,167: topic[/local_control/cancel] adding connection to [http://freight1207:56012/], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,168: topic[/local_control/initialpose] adding connection to [http://freight1207:56012/], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,169: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,170: topic[/local_control/goto] adding connection to [http://freight1207:56012/], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,170: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,171: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,171: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,171: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 20:42:18,234: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2018-12-04 20:42:18,420: topic[/remote_control] adding connection to [/remote_control], count 1
[rosout][WARNING] 2018-12-04 20:43:22,090: publishing data: right to topic /remote_control
[rosout][INFO] 2018-12-04 20:47:14,702: rostful_server: Shutting down the server
[rospy.core][INFO] 2018-12-04 20:47:14,702: signal_shutdown [Closing]
[rospy.internal][INFO] 2018-12-04 20:47:14,708: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 20:47:14,708: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-04 20:47:14,708: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-04 20:47:14,709: Unable to initiate TCP/IP socket to freight1207:52009 (http://freight1207:56012/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 20:47:14,709: Unable to initiate TCP/IP socket to freight1207:52009 (http://freight1207:56012/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 20:47:14,709: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-04 20:47:14,709: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 20:47:14,710: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 20:47:14,710: topic[/remote_control] removing connection to /remote_control
[rospy.internal][INFO] 2018-12-04 20:47:14,710: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 20:47:14,710: topic[/enable_software_runstop] removing connection to http://freight1207:56012/
[rospy.internal][ERROR] 2018-12-04 20:47:14,710: Unable to initiate TCP/IP socket to freight1207:52009 (http://freight1207:56012/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 20:47:14,711: Unable to initiate TCP/IP socket to freight1207:52009 (http://freight1207:56012/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 20:47:14,711: topic[/local_control/initialpose] removing connection to http://freight1207:56012/
[rospy.internal][ERROR] 2018-12-04 20:47:14,711: Unable to initiate TCP/IP socket to freight1207:52009 (http://freight1207:56012/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.topics][ERROR] 2018-12-04 20:47:14,711: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2018-12-04 20:47:14,711: topic[/local_control/goto] removing connection to http://freight1207:56012/
[rospy.internal][INFO] 2018-12-04 20:47:14,711: topic[/remote_control] removing connection to http://freight1207:56012/
[rospy.internal][INFO] 2018-12-04 20:47:14,711: topic[/local_control/cancel] removing connection to http://freight1207:56012/
[rospy.impl.masterslave][INFO] 2018-12-04 20:47:14,712: Closing
[rospy.core][INFO] 2018-12-04 20:47:14,843: signal_shutdown [atexit]
[rospy.client][INFO] 2018-12-04 21:51:57,030: init_node, name[/rostful_server], pid[16124]
[xmlrpc][INFO] 2018-12-04 21:51:57,030: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 21:51:57,030: Started XML-RPC server [http://freight1207:44450/]
[rospy.impl.masterslave][INFO] 2018-12-04 21:51:57,030: _ready: http://freight1207:44450/
[rospy.init][INFO] 2018-12-04 21:51:57,030: ROS Slave URI: [http://freight1207:44450/]
[xmlrpc][INFO] 2018-12-04 21:51:57,031: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 21:51:57,031: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 21:51:57,131: registered with master
[rospy.rosout][INFO] 2018-12-04 21:51:57,131: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 21:51:57,133: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 21:51:57,134: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-04 21:51:57,138: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-04 21:51:57,362: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-04 21:51:58,179: rostful_server: Shutting down the server
[rospy.core][INFO] 2018-12-04 21:51:58,180: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-12-04 21:51:58,183: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2018-12-04 21:51:58,183: atexit
[rospy.client][INFO] 2018-12-04 21:52:10,267: init_node, name[/rostful_server], pid[16456]
[xmlrpc][INFO] 2018-12-04 21:52:10,267: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 21:52:10,267: Started XML-RPC server [http://freight1207:56458/]
[rospy.init][INFO] 2018-12-04 21:52:10,267: ROS Slave URI: [http://freight1207:56458/]
[rospy.impl.masterslave][INFO] 2018-12-04 21:52:10,267: _ready: http://freight1207:56458/
[xmlrpc][INFO] 2018-12-04 21:52:10,268: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 21:52:10,268: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 21:52:10,368: registered with master
[rospy.rosout][INFO] 2018-12-04 21:52:10,368: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 21:52:10,369: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 21:52:10,370: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-04 21:52:10,374: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-04 21:52:10,586: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,419: topic[/enable_software_runstop] adding connection to [/software_runstop], count 0
[rosout][INFO] 2018-12-04 21:52:11,428: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-04 21:52:11,434: topic[/cmd_undock] adding connection to [http://freight1207:56458/], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,435: topic[/cmd_dock] adding connection to [http://freight1207:56458/], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,437: topic[/cmd_undock] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,437: topic[/remote_control] adding connection to [http://freight1207:56458/], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,438: topic[/enable_software_runstop] adding connection to [http://freight1207:56458/], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,439: topic[/cmd_dock] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,439: topic[/local_control/cancel] adding connection to [http://freight1207:56458/], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,440: topic[/local_control/initialpose] adding connection to [http://freight1207:56458/], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,441: topic[/enable_software_runstop] adding connection to [/rostful_server], count 1
[rospy.internal][INFO] 2018-12-04 21:52:11,442: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,442: topic[/local_control/goto] adding connection to [http://freight1207:56458/], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,442: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,443: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,443: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-04 21:52:11,492: topic[/cmd_dock] adding connection to [/dock_on_button], count 1
[rospy.internal][INFO] 2018-12-04 21:52:11,492: topic[/cmd_undock] adding connection to [/undock_on_button], count 1
[rosout][WARNING] 2018-12-04 21:52:23,603: publishing data: True to topic /cmd_dock
[rosout][WARNING] 2018-12-04 21:52:53,472: publishing data: True to topic /cmd_undock
[rosout][WARNING] 2018-12-04 21:54:07,969: publishing data: True to topic /cmd_dock
[rosout][WARNING] 2018-12-04 21:55:11,318: publishing data: True to topic /cmd_undock
[rospy.core][INFO] 2018-12-04 21:57:59,273: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-12-04 21:57:59,277: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-04 21:57:59,277: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 21:57:59,277: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 21:57:59,278: topic[/cmd_dock] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 21:57:59,278: topic[/cmd_dock] removing connection to /dock_on_button
[rospy.internal][ERROR] 2018-12-04 21:57:59,278: Unable to initiate TCP/IP socket to freight1207:57520 (http://freight1207:56458/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 21:57:59,278: Unable to initiate TCP/IP socket to freight1207:57520 (http://freight1207:56458/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 21:57:59,278: Unable to initiate TCP/IP socket to freight1207:57520 (http://freight1207:56458/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 21:57:59,278: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-04 21:57:59,279: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 21:57:59,279: topic[/cmd_undock] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-04 21:57:59,279: topic[/cmd_undock] removing connection to /undock_on_button
[rospy.internal][INFO] 2018-12-04 21:57:59,279: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-04 21:57:59,279: Unable to initiate TCP/IP socket to freight1207:57520 (http://freight1207:56458/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 21:57:59,280: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-04 21:57:59,280: Unable to initiate TCP/IP socket to freight1207:57520 (http://freight1207:56458/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 21:57:59,280: Unable to initiate TCP/IP socket to freight1207:57520 (http://freight1207:56458/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-04 21:57:59,280: Unable to initiate TCP/IP socket to freight1207:57520 (http://freight1207:56458/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-04 21:57:59,280: topic[/enable_software_runstop] removing connection to http://freight1207:56458/
[rospy.internal][INFO] 2018-12-04 21:57:59,280: topic[/local_control/goto] removing connection to http://freight1207:56458/
[rospy.internal][INFO] 2018-12-04 21:57:59,280: topic[/cmd_dock] removing connection to http://freight1207:56458/
[rospy.internal][INFO] 2018-12-04 21:57:59,280: topic[/local_control/initialpose] removing connection to http://freight1207:56458/
[rospy.internal][INFO] 2018-12-04 21:57:59,281: topic[/cmd_undock] removing connection to http://freight1207:56458/
[rospy.internal][INFO] 2018-12-04 21:57:59,281: topic[/remote_control] removing connection to http://freight1207:56458/
[rospy.internal][INFO] 2018-12-04 21:57:59,281: topic[/local_control/cancel] removing connection to http://freight1207:56458/
[rospy.impl.masterslave][INFO] 2018-12-04 21:57:59,281: atexit
