[rospy.client][INFO] 2020-11-03 01:08:25,557: init_node, name[/rostful_server], pid[5288]
[xmlrpc][INFO] 2020-11-03 01:08:25,557: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-03 01:08:25,557: Started XML-RPC server [http://freight1207:34655/]
[rospy.init][INFO] 2020-11-03 01:08:25,557: ROS Slave URI: [http://freight1207:34655/]
[rospy.impl.masterslave][INFO] 2020-11-03 01:08:25,557: _ready: http://freight1207:34655/
[xmlrpc][INFO] 2020-11-03 01:08:25,558: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-03 01:08:25,558: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-03 01:08:25,658: registered with master
[rospy.rosout][INFO] 2020-11-03 01:08:25,658: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-03 01:08:25,659: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-03 01:08:25,660: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-03 01:08:25,664: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-03 01:08:25,896: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2020-11-03 01:08:26,707: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-03 01:08:26,724: topic[/enable_software_runstop] adding connection to [http://freight1207:34655/], count 0
[rospy.internal][INFO] 2020-11-03 01:08:26,725: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:08:26,741: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rosout][INFO] 2020-11-03 01:09:23,092: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-03 01:09:23,092: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-03 01:09:23,094: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:09:23,094: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-11-03 01:09:23,094: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-03 01:09:23,095: topic[/enable_software_runstop] removing connection to http://freight1207:34655/
[rospy.impl.masterslave][INFO] 2020-11-03 01:09:23,095: Closing
[rospy.internal][ERROR] 2020-11-03 01:09:23,096: Unable to initiate TCP/IP socket to freight1207:44338 (http://freight1207:34655/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2020-11-03 01:09:23,198: signal_shutdown [atexit]
[rospy.client][INFO] 2020-11-03 01:09:45,028: init_node, name[/rostful_server], pid[6022]
[xmlrpc][INFO] 2020-11-03 01:09:45,028: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-03 01:09:45,029: Started XML-RPC server [http://freight1207:43521/]
[rospy.init][INFO] 2020-11-03 01:09:45,029: ROS Slave URI: [http://freight1207:43521/]
[rospy.impl.masterslave][INFO] 2020-11-03 01:09:45,029: _ready: http://freight1207:43521/
[xmlrpc][INFO] 2020-11-03 01:09:45,029: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-03 01:09:45,029: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-03 01:09:45,129: registered with master
[rospy.rosout][INFO] 2020-11-03 01:09:45,129: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-03 01:09:45,131: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-03 01:09:45,132: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-03 01:09:45,136: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-03 01:09:45,404: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,197: topic[/current/pose] adding connection to [http://freight1207:43521/], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,198: topic[/enable_software_runstop] adding connection to [http://freight1207:43521/], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,199: topic[/local_control/cancel] adding connection to [http://freight1207:43521/], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,200: topic[/local_control/initialpose] adding connection to [http://freight1207:43521/], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,201: topic[/local_control/goto] adding connection to [http://freight1207:43521/], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,201: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,202: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,202: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,202: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,203: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:09:46,221: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rosout][INFO] 2020-11-03 01:09:46,463: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-03 01:09:49,912: topic[/current/pose] adding connection to [http://freight1207:53204/], count 1
[rospy.internal][INFO] 2020-11-03 01:09:50,111: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-03 01:09:50,112: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-03 01:09:50,112: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rosout][WARNING] 2020-11-03 01:09:56,403: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -7.32
    locationY: -2.51
    orientation: 0.102
  - 
    locationX: -5.89
    locationY: -1.99
    orientation: 0.17 to topic /local_control/goto
[rosout][WARNING] 2020-11-03 01:10:25,629: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -7.32
    locationY: -2.51
    orientation: 0.102
  - 
    locationX: -5.89
    locationY: -1.99
    orientation: 0.17 to topic /local_control/goto
[rospy.internal][WARNING] 2020-11-03 01:11:17,506: Unknown error initiating TCP/IP socket to freight1207:49198 (http://freight1207:53204/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-03 01:11:17,506: topic[/current/pose] removing connection to http://freight1207:53204/
[rosout][INFO] 2020-11-03 01:11:22,349: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-03 01:11:22,350: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-03 01:11:22,353: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:11:22,353: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][ERROR] 2020-11-03 01:11:22,354: Unable to initiate TCP/IP socket to freight1207:56326 (http://freight1207:43521/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:11:22,354: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:11:22,354: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-11-03 01:11:22,354: Unable to initiate TCP/IP socket to freight1207:56326 (http://freight1207:43521/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:11:22,354: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-03 01:11:22,355: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:11:22,355: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-11-03 01:11:22,355: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:11:22,355: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][INFO] 2020-11-03 01:11:22,355: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:11:22,356: topic[/enable_software_runstop] removing connection to http://freight1207:43521/
[rospy.internal][ERROR] 2020-11-03 01:11:22,356: Unable to initiate TCP/IP socket to freight1207:56326 (http://freight1207:43521/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-11-03 01:11:22,356: Unable to initiate TCP/IP socket to freight1207:56326 (http://freight1207:43521/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:11:22,356: topic[/local_control/initialpose] removing connection to http://freight1207:43521/
[rospy.internal][ERROR] 2020-11-03 01:11:22,356: Unable to initiate TCP/IP socket to freight1207:56326 (http://freight1207:43521/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:11:22,356: topic[/local_control/goto] removing connection to http://freight1207:43521/
[rospy.internal][INFO] 2020-11-03 01:11:22,356: topic[/local_control/cancel] removing connection to http://freight1207:43521/
[rospy.internal][INFO] 2020-11-03 01:11:22,356: topic[/current/pose] removing connection to http://freight1207:43521/
[rospy.impl.masterslave][INFO] 2020-11-03 01:11:22,357: Closing
[rospy.core][INFO] 2020-11-03 01:11:22,458: signal_shutdown [atexit]
[rospy.client][INFO] 2020-11-03 01:30:40,631: init_node, name[/rostful_server], pid[5475]
[xmlrpc][INFO] 2020-11-03 01:30:40,632: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-03 01:30:40,632: Started XML-RPC server [http://freight1207:53173/]
[rospy.init][INFO] 2020-11-03 01:30:40,632: ROS Slave URI: [http://freight1207:53173/]
[rospy.impl.masterslave][INFO] 2020-11-03 01:30:40,632: _ready: http://freight1207:53173/
[xmlrpc][INFO] 2020-11-03 01:30:40,633: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-03 01:30:40,633: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-03 01:30:40,732: registered with master
[rospy.rosout][INFO] 2020-11-03 01:30:40,732: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-03 01:30:40,734: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-03 01:30:40,735: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-03 01:30:40,739: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-03 01:30:41,027: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,800: topic[/current/pose] adding connection to [http://freight1207:53173/], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,801: topic[/enable_software_runstop] adding connection to [http://freight1207:53173/], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,802: topic[/local_control/cancel] adding connection to [http://freight1207:53173/], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,803: topic[/local_control/goto] adding connection to [http://freight1207:53173/], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,804: topic[/local_control/initialpose] adding connection to [http://freight1207:53173/], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,805: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,806: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,806: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,806: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 01:30:41,806: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rosout][INFO] 2020-11-03 01:30:41,841: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-03 01:30:41,874: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2020-11-03 01:31:39,526: topic[/current/pose] adding connection to [http://freight1207:50548/], count 1
[rospy.internal][INFO] 2020-11-03 01:31:39,703: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2020-11-03 01:31:39,703: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-03 01:31:39,704: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rosout][WARNING] 2020-11-03 01:31:49,805: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.36
    locationY: -3.52
    orientation: 0.23
  - 
    locationX: -9.22
    locationY: -3.04
    orientation: 0.201 to topic /local_control/goto
[rosout][WARNING] 2020-11-03 01:32:01,118: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.36
    locationY: -3.52
    orientation: 0.23
  - 
    locationX: -9.22
    locationY: -3.04
    orientation: 0.201 to topic /local_control/goto
[rospy.internal][WARNING] 2020-11-03 01:32:19,457: Unknown error initiating TCP/IP socket to freight1207:41760 (http://freight1207:50548/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-03 01:32:19,457: topic[/current/pose] removing connection to http://freight1207:50548/
[rosout][INFO] 2020-11-03 01:32:23,655: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-03 01:32:23,655: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-03 01:32:23,658: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:32:23,659: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-11-03 01:32:23,659: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:32:23,659: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-11-03 01:32:23,659: Unable to initiate TCP/IP socket to freight1207:55414 (http://freight1207:53173/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:32:23,659: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-03 01:32:23,660: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-11-03 01:32:23,660: Unable to initiate TCP/IP socket to freight1207:55414 (http://freight1207:53173/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:32:23,660: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-11-03 01:32:23,660: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-11-03 01:32:23,660: Unable to initiate TCP/IP socket to freight1207:55414 (http://freight1207:53173/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:32:23,660: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-11-03 01:32:23,661: Unable to initiate TCP/IP socket to freight1207:55414 (http://freight1207:53173/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:32:23,661: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 01:32:23,661: topic[/enable_software_runstop] removing connection to http://freight1207:53173/
[rospy.internal][INFO] 2020-11-03 01:32:23,661: topic[/local_control/initialpose] removing connection to http://freight1207:53173/
[rospy.internal][INFO] 2020-11-03 01:32:23,661: topic[/local_control/goto] removing connection to http://freight1207:53173/
[rospy.internal][INFO] 2020-11-03 01:32:23,661: topic[/local_control/cancel] removing connection to http://freight1207:53173/
[rospy.internal][ERROR] 2020-11-03 01:32:23,661: Unable to initiate TCP/IP socket to freight1207:55414 (http://freight1207:53173/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 01:32:23,662: topic[/current/pose] removing connection to http://freight1207:53173/
[rospy.impl.masterslave][INFO] 2020-11-03 01:32:23,662: Closing
[rospy.core][INFO] 2020-11-03 01:32:23,793: signal_shutdown [atexit]
