[rospy.client][INFO] 2020-11-02 19:43:49,362: init_node, name[/rostopic_10833_1604375029342], pid[10833]
[xmlrpc][INFO] 2020-11-02 19:43:49,362: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-02 19:43:49,362: Started XML-RPC server [http://freight1207:40028/]
[rospy.init][INFO] 2020-11-02 19:43:49,362: ROS Slave URI: [http://freight1207:40028/]
[rospy.impl.masterslave][INFO] 2020-11-02 19:43:49,363: _ready: http://freight1207:40028/
[xmlrpc][INFO] 2020-11-02 19:43:49,363: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-02 19:43:49,363: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-02 19:43:49,463: registered with master
[rospy.rosout][INFO] 2020-11-02 19:43:49,463: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-02 19:43:49,464: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-02 19:43:49,465: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-02 19:43:49,676: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-02 19:43:55,042: topic[/amcl_pose] adding connection to [http://freight1207:53761/], count 0
[rospy.core][INFO] 2020-11-02 19:44:02,558: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-02 19:44:02,560: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-02 19:44:02,560: topic[/amcl_pose] removing connection to http://freight1207:53761/
[rospy.internal][WARNING] 2020-11-02 19:44:02,560: Unknown error initiating TCP/IP socket to freight1207:53937 (http://freight1207:53761/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-11-02 19:44:02,562: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2020-11-02 19:44:02,562: signal-2
[rospy.core][INFO] 2020-11-02 19:44:03,176: signal_shutdown [atexit]
