[rospy.client][INFO] 2018-12-04 20:28:40,699: init_node, name[/rostopic_2292_1543984120684], pid[2292]
[xmlrpc][INFO] 2018-12-04 20:28:40,700: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 20:28:40,700: Started XML-RPC server [http://freight1207:42698/]
[rospy.init][INFO] 2018-12-04 20:28:40,700: ROS Slave URI: [http://freight1207:42698/]
[rospy.impl.masterslave][INFO] 2018-12-04 20:28:40,700: _ready: http://freight1207:42698/
[rospy.registration][INFO] 2018-12-04 20:28:40,700: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2018-12-04 20:28:40,700: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2018-12-04 20:28:40,800: registered with master
[rospy.rosout][INFO] 2018-12-04 20:28:40,800: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 20:28:40,802: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 20:28:40,803: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2018-12-04 20:28:40,815: topic[/teleop/cmd_vel] adding connection to [http://freight1207:38439/], count 0
[rospy.internal][INFO] 2018-12-04 20:28:40,929: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2018-12-04 20:28:47,580: signal_shutdown [signal-2]
[rospy.internal][INFO] 2018-12-04 20:28:47,583: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-04 20:28:47,583: topic[/teleop/cmd_vel] removing connection to http://freight1207:38439/
[rospy.internal][WARNING] 2018-12-04 20:28:47,584: Unknown error initiating TCP/IP socket to freight1207:46595 (http://freight1207:38439/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2018-12-04 20:28:47,584: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2018-12-04 20:28:47,584: signal-2
[rospy.core][INFO] 2018-12-04 20:28:47,748: signal_shutdown [atexit]
